### ISSUE TITLE
Hello, I tested your code on the Indian dataset. Take 20% of the dataset, AA is very low, only 93%. Then I found that the classification result of some classes is 0.

### ISSUE THREAD

**Issue by guozhen123** [zilongzhong/SSRN#14]
Hello, I tested your code on the Indian dataset. Take 20% of the dataset, AA is very low, only 93%. Then I found that the classification result of some classes is 0.

**Comment by zilongzhong** [comment]
Classification performance also depends on how many epochs you trained. For more training and testing details, please check the paper https://ieeexplore.ieee.org/abstract/document/8061020
