### ISSUE TITLE
I can only run one epoch by running `SSRN_IN.py`

### ISSUE THREAD

**Issue by darrenzhang1007** [zilongzhong/SSRN#18]
Hello teacher, I meet a problem.
I use Python 3.6 + keras-2.2.4 .
I can only run one epoch when run `SSRN_IN.py`,  Then the code was interrupted. But there is no error,
![微信截图_20190926151727](https://user-images.githubusercontent.com/44083987/65666684-c2c28e00-e070-11e9-999d-c23f5de90ca2.png)
how can i to revised it? Thanks. @zilongzhong

**Comment by zilongzhong** [comment]
I can run the codes without such a problem. Make sure you have the same conda environment setting.

Best regards,
Zilong

**Comment by darrenzhang1007** [comment]
Before, I used the environment: cudn10+tensorflow14.It didn`t work.
Now, I set my environment: cudn9.2+tensorflow1.8. This problem can solve. 
Thanks,
