### ISSUE TITLE
Does code work on CPU please tell me

### ISSUE THREAD

**Issue by radhesyam** [zilongzhong/SSRN#5]
your cpu supports instructions that this tensorflow binary was not compiled to use: avx2 fma

taking longer time to train

Does it work on CPU please tell me

**Comment by zilongzhong** [comment]
I only used GPU for this project because each SSRN model contains about 360,000 parameters to train. More importantly, GPUs are essential for deep learning.

**Comment by radhesyam** [comment]
in Running SSRN_IN.py the following error encountered
from Utils import zeroPadding, normalization, doPCA, modelStatsRecord, averageAccuracy, ssrn_SS_IN
since Utils is folder i am getting **import error**
